// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace WebSiteTest.Areas.ProductsFront.Models
{
    public partial class ComperWebSiteContext : DbContext
    {
        public ComperWebSiteContext()
        {
        }

        public ComperWebSiteContext(DbContextOptions<ComperWebSiteContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<FavoriteList> FavoriteList { get; set; }
        public virtual DbSet<OrderDetail> OrderDetail { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<ShoppingCart> ShoppingCart { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Customers>(entity =>
            {
                entity.HasKey(e => e.CustomerId);

                entity.Property(e => e.CustomerId)
                    .HasMaxLength(50)
                    .HasColumnName("CustomerID");

                entity.Property(e => e.CAccount)
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnName("C_Account");

                entity.Property(e => e.CAddDate)
                    .HasColumnType("datetime")
                    .HasColumnName("C_AddDate");

                entity.Property(e => e.CAddress)
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnName("C_Address");

                entity.Property(e => e.CBirth)
                    .HasColumnType("datetime")
                    .HasColumnName("C_Birth");

                entity.Property(e => e.CEmail)
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnName("C_Email");

                entity.Property(e => e.CNotes).HasColumnName("C_Notes");

                entity.Property(e => e.CPassWord)
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnName("C_PassWord");

                entity.Property(e => e.CPhone)
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnName("C_Phone");

                entity.Property(e => e.CustomerName)
                    .IsRequired()
                    .HasMaxLength(100);
            });

            modelBuilder.Entity<FavoriteList>(entity =>
            {
                entity.HasKey(e => new { e.CustomerId, e.ProductId });

                entity.Property(e => e.CustomerId).HasMaxLength(50);

                entity.Property(e => e.ProductId).HasMaxLength(50);
            });

            modelBuilder.Entity<OrderDetail>(entity =>
            {
                entity.HasKey(e => new { e.OrderId, e.ProductId });

                entity.Property(e => e.OrderId)
                    .HasMaxLength(50)
                    .HasColumnName("OrderID");

                entity.Property(e => e.ProductId)
                    .HasMaxLength(50)
                    .HasColumnName("ProductID");

                entity.HasOne(d => d.Order)
                    .WithMany(p => p.OrderDetail)
                    .HasForeignKey(d => d.OrderId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_OrderDetail_Orders1");
            });

            modelBuilder.Entity<Orders>(entity =>
            {
                entity.HasKey(e => e.OrderId);

                entity.Property(e => e.OrderId)
                    .HasMaxLength(50)
                    .HasColumnName("OrderID");

                entity.Property(e => e.CustomerId)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("CustomerID");

                entity.Property(e => e.EmployeeId)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("EmployeeID");

                entity.Property(e => e.OrderOnDate).HasColumnType("datetime");

                entity.Property(e => e.OrderStatus)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.ShipAddress).IsRequired();

                entity.Property(e => e.ShipDate).HasColumnType("datetime");

                entity.Property(e => e.ShippingMethod)
                    .IsRequired()
                    .HasMaxLength(50);
            });

            modelBuilder.Entity<ShoppingCart>(entity =>
            {
                entity.HasKey(e => new { e.CustomerId, e.ProductId });

                entity.Property(e => e.CustomerId).HasMaxLength(50);

                entity.Property(e => e.ProductId).HasMaxLength(50);

                entity.Property(e => e.ProductQty).HasDefaultValueSql("((1))");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}