// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebSiteTest.Areas.ProductsFront.Models
{
    public partial class ShoppingCart
    {
        public string CustomerId { get; set; }
        public string ProductId { get; set; }
        public int ProductQty { get; set; }
        public int ProductUnitPrice { get; set; }
    }
}